Square63/audiosocket_frontend_phase4

components/Tracks.js

Hide follow artist button for sfx and loaded alternate version tracks on click

---

components/Header.js
styles/globals.scss

Task Link: https://app.asana.com/0/1200582265762772/1202579348517976

Header: fixed sign up button text disappearing on hover and active.

---

components/SelectPricingPlan.js
pages/index.js

Task Link: https://app.asana.com/0/1200582265762772/1202579348517971

Index/Pricing: Updated links for ContactSales button.

---

components/modals/ShareModal.js

Task Link: https://app.asana.com/0/1200582265762772/1200835724941155

Playlists: Added functionality to copy playlist link on share modal.

---

components/FavoriteTracks.js

Task Link: https://app.asana.com/0/1200582265762772/1202548922269558

Favorites: Added functionlity for Tracks and Sfxs toggle.

---

components/FavoriteTracks.js
components/Footer.js
components/SelectPricingPlan.js
components/SingleAudioWave.js
components/Tracks.js
pages/cart.js
pages/index.js
pages/playlist/curatedPlaylist.js
pages/playlist/similarSearch.js
pages/user/subscription.js
styles/globals.scss

Task Links:-
- https://app.asana.com/0/1200582265762772/1202566511274106
- https://app.asana.com/0/1200582265762772/1202600960514946
- https://app.asana.com/0/1200582265762772/1202600960514911
- https://app.asana.com/0/1200582265762772/1202600960267090
- https://app.asana.com/0/1200582265762772/1202600960267107
- https://app.asana.com/0/1200582265762772/1202600960514905
- https://app.asana.com/0/1200582265762772/1202600960267095

Completed multiple minor tasks in client feedback column.

---

components/Footer.js
pages/index.js
pages/search.js

Tasks Links:-
- https://app.asana.com/0/1200582265762772/1202565532143758
- https://app.asana.com/0/1200582265762772/1202600960514930
- Remove clickable link from info icon on the index page.

Multiple minor tasks implemented.

---

components/MyPlaylistTracks.js
components/Tracks.js
pages/cart.js
pages/playlist/curatedPlaylist/[id].js
pages/playlist/myPlaylists.js
pages/playlist/myPlaylists/[id].js
pages/sfx.js

Task Links:-
- https://app.asana.com/0/1200582265762772/1202565532143770
- https://app.asana.com/0/1200582265762772/1202607404254136
- https://app.asana.com/0/1200582265762772/1202566511274135
- https://app.asana.com/0/1200582265762772/1202565532143758
- https://app.asana.com/0/1200582265762772/1202548922269616

Implemented multiple minor tasks.

---

components/CreatorKitsTracks.js
components/MyPlaylistTracks.js
components/Tracks.js
components/modals/ShareModal.js
pages/playlist/[id].js
pages/playlist/creatorKits/[id].js
pages/playlist/myPlaylists/[id].js
pages/search/[id].js

Task Link: https://app.asana.com/0/1200582265762772/1202600960267101

Implemented share button throughout website.

---

pages/playlist/MyPlaylistShow.js
pages/playlist/myPlaylists/[id].js

Task Link: https://app.asana.com/0/1200582265762772/1202566511274125

Removed clickable cursor from artists on this album

---

components/SelectPricingPlan.js
components/Sidebar.js

Task Link: https://app.asana.com/0/1200582265762772/1202565532143651

Pricing: Fixed pricing plans incorrect payable amount issue.

---

components/profile/ProfileForm.js
components/profile/Settings.js
redux/actions/authActions.js

Task Link: https://app.asana.com/0/1200582265762772/1202600960514917

Profile: Added functionality to update YouTube whitelisting toggle.

---

components/profile/Settings.js

Task Link: https://app.asana.com/0/1200582265762772/1202600960514917

PR feedback incorporated

---

components/Footer.js
pages/index.js
pages/playlist/creatorKits/[id].js
pages/playlist/curatedPlaylist/[id].js

Task Links:-
- https://app.asana.com/0/1200582265762772/1202565532143703
- https://app.asana.com/0/1200582265762772/1202616805750448
- https://app.asana.com/0/1200582265762772/1202616805750378
- https://app.asana.com/0/1200582265762772/1202616805750370
- https://app.asana.com/0/1200582265762772/1202616805678197

Multiple minor fixes done.

---

components/modals/DownloadPlaylist.js

Task Link: https://app.asana.com/0/1200582265762772/1202616805750402

Updated text and close timer for download playlist madal.

---

pages/user/subscription.js
styles/User.module.scss
styles/variables-mixins.scss

Task Link: https://app.asana.com/0/1200582265762772/1202548922269736

Implemented pricing plans on subscription page.

---

components/Footer.js
components/SelectPricingPlan.js
pages/index.js
pages/playlist/creatorKits/[id].js
pages/playlist/curatedPlaylist/[id].js
pages/playlist/myPlaylists/[id].js
pages/search.js
pages/search/[id].js
pages/sfx.js
pages/user/favorites.js

Task Links:-
- https://app.asana.com/0/1200582265762772/1202636020601929
- https://app.asana.com/0/1200582265762772/1202636020601919
- https://app.asana.com/0/1200582265762772/1202636020601913

Added ASX Film/TV link to footer and updated text in a few places.

---

pages/indieFilm.js
pages/individualLicense.js
pages/largeBusiness.js
pages/smallBusiness.js

Task Link: https://app.asana.com/0/1200582265762772/1202542464311317/f

Added back button to all single license agreement pages

---

pages/index.js

Task Link: https://app.asana.com/0/1200582265762772/1202636020601935

Index: updated videos

---

components/Footer.js
pages/indieFilm.js
pages/individualLicense.js
pages/largeBusiness.js
pages/smallBusiness.js

Task Link: https://app.asana.com/0/1200582265762772/1202636020601942

Added Technology section to footer and resolved build issues

---

pages/user/licenses.js

Reverts Square63/audiosocket_frontend_phase4#229

Revert "Displayed time instead of date in licenses"

---

components/Header.js

Task Link: https://app.asana.com/0/1200582265762772/1202636020601953

Header: Updated Account dropdown options.

---

components/SelectPricingPlan.js
pages/indieFilm.js
pages/individualLicense.js
pages/largeBusiness.js
pages/smallBusiness.js

Task Link: https://app.asana.com/0/1200582265762772/1202542464311317

Pricing: fixed redirection from licenses page to respective plan type
